name: Build and Test

on:
    pull_request:

jobs:
    Setup:
        runs-on: ubuntu-latest
        outputs:
            cache-key: ${{ steps.cache-keys.outputs.key }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.9.0"

            - name: Install dependencies
              run: npm install

            - name: Save node modules
              uses: actions/upload-artifact@v4
              with:
                  name: node-modules
                  path: node_modules

    Test:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' # This line ensures that this job only runs on pull requests
        needs: Setup
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download node modules
              uses: actions/download-artifact@v4
              with:
                  name: node-modules
                  path: node_modules

            - name: Install HardHat
              run: npm i hardhat

            - name: Run tests
              run: npx hardhat test

    Coverage-Test:
        runs-on: ubuntu-latest
        needs: Setup
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download node modules
              uses: actions/download-artifact@v4
              with:
                  name: node-modules
                  path: node_modules
                  
            - name: Install HardHat
              run: npm i hardhat

            - name: Run tests and generate coverage
              run: npx hardhat coverage

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
